### ISSUE TITLE
labels position overflow problem after the start 

### ISSUE THREAD

**Issue by ebubekirtabak** [soanvig/jsr#43]
Hi,

[![ISlider issue](https://img.youtube.com/vi/RmcvJal_5x0/0.jpg)](https://www.youtube.com/watch?v=RmcvJal_5x0)

does not add its size when the labels are separated.

**Comment by soanvig** [comment]
Thank you for bug report. Unfortunately I cannot play that video

**Comment by soanvig** [comment]
I see. Can you provide with some minimal code reproduction?

**Comment by ebubekirtabak** [comment]
Hi, I solved this issue. no error in code.Width calculation is not true because parent element is not a block. parent width is 0px on before init slider. I've changed the top element style to 'display: none' 'visibility: invisible'.
Thanks
