### ISSUE TITLE
Is it expected that the npm distribution requires babel plugins etc.. 

### ISSUE THREAD

**Issue by mccainz** [soanvig/jsr#44]
I noticed that after adding an NPM dependency for mm-jsr 1.1.15 in my package.json, the corresponding package.lock.json file now has numerous entries for babel-plugin-transform-* related packages required by babel-preset-es2015-rollup as well as an entry for grunt-contrib-copy. Is this expected? Are these actually runtime dependencies or can they be removed?

**Comment by soanvig** [comment]
This is the bug. Babel preset should not be in dependencies, but in devDependencies.

Could catch. I'll release corrected version in a while.

**Comment by soanvig** [comment]
By the way, as stated in README, JSR v1 is legacy, not expanded anymore.

See https://gitlab.com/soanvig/jsr/ which is not ready yet, still missing some features from v1, but close to production state.

**Comment by soanvig** [comment]
Done, 1.1.6 version is published.
