### ISSUE TITLE
README: wrong path to css

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soanvig/jsr#49]
In documentation: `/dist/assets/css/mm-jsr.css`.

Correct path is `/dist/assets/css/main.css`

**Comment by soanvig** [comment]
Sorry for no reponses :-)

The project (v1) is not maintained anymore.

I have it on my personal roadmap to refactor it. I've looked today at it, and found some motivation to correct everything, that was designed badly in v2.

**Comment by soanvig** [comment]
Not relevant for v2
