### ISSUE TITLE
Friendly defaults or config validation at least

### ISSUE THREAD

**Issue by YuriGor** [soanvig/jsr#51]
Hi, you have a lot of required options in the constructor, but they are not required explicitly, frustrating a bit and causing a lot of time losses.
- `options` parameter - if it's absolutely required (but intuitively I expect if I pass a single dom element it should work with default options) then check if it's not undefined in the constructor, please.
- `values` - why not to set them as 0 by default? Or throw a meaningful error at least. Now if no `values` field specified in options object - some "cannot get length from undefined" error appears with no idea what's going on. Check if it's not `undefined` in the constructor, please
- `sliders` - why do you need this count? I pass an array with dom elements, you can get the length of this array? Or to validate what did you find by given CSS selector? Then again check if `sliders` is not undefined, otherwise throw an error it's required.
Without such options validation, there are a lot of errors thrown from the depths of the minified component, so it's frustrating. 
Usually looking into docs is the last idea, first, you will hope error message will say what's wrong.
If error looks like not expected by the author (it looks so in the cases above) - then you will try to look into the sources right in the browser (because it's an open-source software) and you will see minified version only (that's why I asked for src in npm package in another issue)

By the way, a quick question - is there any chance to init range with not attached to the body element?

**Comment by soanvig** [comment]
Sorry for no reponses :-)

The project is not maintained anymore.

I have it on my personal roadmap to refactor it. I've looked today at it, and found some motivation to correct everything, that was designed badly in v2.

**Comment by YuriGor** [comment]
Up to you, no issue from my side :)

**Comment by soanvig** [comment]
Ready in v2 :) And the v2 is almost ready too, stay tuned
